disabled_rules:
  - line_length
  - trailing_whitespace
  - nesting
  - number_separator
  - comment_spacing
  - function_body_length
  - function_parameter_count

opt_in_rules:
  - anyobject_protocol
  - let_var_whitespace
  - file_name
  - file_name_no_space
  - vertical_whitespace_opening_braces
  - vertical_whitespace_closing_braces

included:

excluded:
  - Pods
  - HaluEumpyo/App/AppDelegate
  - HaluEumpyo/App/SceneDelegate
  - HaluEumpyoTests
  - HaluEumpyoUITests

identifier_name:
  min_length:
    error: 3
  excluded:
    - id

force_cast: warning
    
